SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgsodium";
COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
SET default_tablespace = '';
SET default_table_access_method = "heap";
CREATE TABLE IF NOT EXISTS "public"."ad_agencies" (
                                                      "id" bigint NOT NULL,
                                                      "contact_id" bigint NOT NULL,
                                                      "name" "text" NOT NULL,
                                                      "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."ad_agencies" OWNER TO "postgres";
ALTER TABLE "public"."ad_agencies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ad_agency_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."ad_campaigns" (
                                                       "id" bigint NOT NULL,
                                                       "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
                                                       "audience_group_id" bigint,
                                                       "name" "text" NOT NULL,
                                                       "media_company_id" bigint NOT NULL,
                                                       "ad_id" bigint NOT NULL
);
ALTER TABLE "public"."ad_campaigns" OWNER TO "postgres";
ALTER TABLE "public"."ad_campaigns" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ad_campaign_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."advertisments" (
                                                        "id" bigint NOT NULL,
                                                        "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."advertisments" OWNER TO "postgres";
ALTER TABLE "public"."advertisments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ad_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."audience_groups" (
                                                          "id" bigint NOT NULL,
                                                          "name" "text" NOT NULL,
                                                          "description" "text",
                                                          "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
                                                          "modified" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
                                                          "demographic_id" bigint NOT NULL
);
ALTER TABLE "public"."audience_groups" OWNER TO "postgres";
COMMENT ON TABLE "public"."audience_groups" IS 'target audiences for an ad campaign';
ALTER TABLE "public"."audience_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."audience_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."demographics" (
                                                       "id" bigint NOT NULL,
                                                       "age_start" integer,
                                                       "age_end" integer,
                                                       "description" "text",
                                                       "gender" "text",
                                                       "zip" "text",
                                                       "geo_data" "text",
                                                       "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
                                                       "modified" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);
ALTER TABLE "public"."demographics" OWNER TO "postgres";
COMMENT ON TABLE "public"."demographics" IS 'basic identifying traits for an individual';
COMMENT ON COLUMN "public"."demographics"."geo_data" IS 'geo coordinates for a region';
ALTER TABLE "public"."demographics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."demographics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."media_companies" (
                                                          "id" bigint NOT NULL,
                                                          "contact_id" bigint,
                                                          "name" "text" NOT NULL,
                                                          "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
                                                          "modified" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);
ALTER TABLE "public"."media_companies" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."media_company_descriptors" (
                                                                    "id" bigint NOT NULL,
                                                                    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."media_company_descriptors" OWNER TO "postgres";
ALTER TABLE "public"."media_company_descriptors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_company_descriptors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
ALTER TABLE "public"."media_companies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."programs" (
                                                   "id" bigint NOT NULL,
                                                   "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."programs" OWNER TO "postgres";
ALTER TABLE "public"."programs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."program_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."regions" (
                                                  "id" bigint NOT NULL,
                                                  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."regions" OWNER TO "postgres";
ALTER TABLE "public"."regions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."regions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."seasons" (
                                                  "id" bigint NOT NULL,
                                                  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."seasons" OWNER TO "postgres";
ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."seasons_programs" (
                                                           "id" bigint NOT NULL,
                                                           "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."seasons_programs" OWNER TO "postgres";
ALTER TABLE "public"."seasons_programs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_programs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."sinclair_affiliates" (
                                                              "id" bigint NOT NULL,
                                                              "market" "text",
                                                              "stations" "text",
                                                              "affiliations" "text",
                                                              "status" "text",
                                                              "dma_rank" integer,
                                                              "links" "text",
                                                              "links_svg" "text",
                                                              "links_link" "text",
                                                              "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
                                                              "modified" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
                                                              "created_by" bigint DEFAULT 1,
                                                              "modified_by" bigint DEFAULT 1
);
ALTER TABLE "public"."sinclair_affiliates" OWNER TO "postgres";
COMMENT ON TABLE "public"."sinclair_affiliates" IS 'Sinclair broadcasting affiliates';
ALTER TABLE "public"."sinclair_affiliates" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."sinclair_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."timeslots" (
                                                    "id" bigint NOT NULL,
                                                    "created" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);
ALTER TABLE "public"."timeslots" OWNER TO "postgres";
ALTER TABLE "public"."timeslots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."timeslot_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
CREATE TABLE IF NOT EXISTS "public"."timeslot_purchases" (
                                                             "id" bigint NOT NULL,
                                                             "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."timeslot_purchases" OWNER TO "postgres";
ALTER TABLE "public"."timeslot_purchases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."timeslot_purchase_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
ALTER TABLE ONLY "public"."ad_agencies"
    ADD CONSTRAINT "ad_agency_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ad_campaigns"
    ADD CONSTRAINT "ad_campaign_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."advertisments"
    ADD CONSTRAINT "ad_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."audience_groups"
    ADD CONSTRAINT "audience_groups_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."demographics"
    ADD CONSTRAINT "demographics_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."media_company_descriptors"
    ADD CONSTRAINT "media_company_descriptors_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."media_companies"
    ADD CONSTRAINT "media_company_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."programs"
    ADD CONSTRAINT "program_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."regions"
    ADD CONSTRAINT "regions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."seasons_programs"
    ADD CONSTRAINT "seasons_programs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."sinclair_affiliates"
    ADD CONSTRAINT "sinclair_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."timeslots"
    ADD CONSTRAINT "timeslot_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."timeslot_purchases"
    ADD CONSTRAINT "timeslot_purchase_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ad_campaigns"
    ADD CONSTRAINT "ad_campaigns_ad_id_fkey" FOREIGN KEY ("ad_id") REFERENCES "public"."advertisments"("id");
ALTER TABLE ONLY "public"."ad_campaigns"
    ADD CONSTRAINT "ad_campaigns_audience_group_id_fkey" FOREIGN KEY ("audience_group_id") REFERENCES "public"."audience_groups"("id");
ALTER TABLE ONLY "public"."ad_campaigns"
    ADD CONSTRAINT "ad_campaigns_media_company_id_fkey" FOREIGN KEY ("media_company_id") REFERENCES "public"."media_companies"("id");
ALTER TABLE ONLY "public"."audience_groups"
    ADD CONSTRAINT "audience_groups_demographic_id_fkey" FOREIGN KEY ("demographic_id") REFERENCES "public"."demographics"("id") ON UPDATE CASCADE ON DELETE CASCADE;
CREATE POLICY "Enable read access for all users" ON "public"."audience_groups" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."sinclair_affiliates" FOR SELECT USING (true);
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON TABLE "public"."ad_agencies" TO "anon";
GRANT ALL ON TABLE "public"."ad_agencies" TO "authenticated";
GRANT ALL ON TABLE "public"."ad_agencies" TO "service_role";
GRANT ALL ON SEQUENCE "public"."ad_agency_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ad_agency_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ad_agency_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."ad_campaigns" TO "anon";
GRANT ALL ON TABLE "public"."ad_campaigns" TO "authenticated";
GRANT ALL ON TABLE "public"."ad_campaigns" TO "service_role";
GRANT ALL ON SEQUENCE "public"."ad_campaign_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ad_campaign_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ad_campaign_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."advertisments" TO "anon";
GRANT ALL ON TABLE "public"."advertisments" TO "authenticated";
GRANT ALL ON TABLE "public"."advertisments" TO "service_role";
GRANT ALL ON SEQUENCE "public"."ad_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ad_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ad_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."audience_groups" TO "anon";
GRANT ALL ON TABLE "public"."audience_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."audience_groups" TO "service_role";
GRANT ALL ON SEQUENCE "public"."audience_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audience_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audience_groups_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."demographics" TO "anon";
GRANT ALL ON TABLE "public"."demographics" TO "authenticated";
GRANT ALL ON TABLE "public"."demographics" TO "service_role";
GRANT ALL ON SEQUENCE "public"."demographics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."demographics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."demographics_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."media_companies" TO "anon";
GRANT ALL ON TABLE "public"."media_companies" TO "authenticated";
GRANT ALL ON TABLE "public"."media_companies" TO "service_role";
GRANT ALL ON TABLE "public"."media_company_descriptors" TO "anon";
GRANT ALL ON TABLE "public"."media_company_descriptors" TO "authenticated";
GRANT ALL ON TABLE "public"."media_company_descriptors" TO "service_role";
GRANT ALL ON SEQUENCE "public"."media_company_descriptors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_company_descriptors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_company_descriptors_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."media_company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_company_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."programs" TO "anon";
GRANT ALL ON TABLE "public"."programs" TO "authenticated";
GRANT ALL ON TABLE "public"."programs" TO "service_role";
GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."regions" TO "anon";
GRANT ALL ON TABLE "public"."regions" TO "authenticated";
GRANT ALL ON TABLE "public"."regions" TO "service_role";
GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."seasons" TO "anon";
GRANT ALL ON TABLE "public"."seasons" TO "authenticated";
GRANT ALL ON TABLE "public"."seasons" TO "service_role";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."seasons_programs" TO "anon";
GRANT ALL ON TABLE "public"."seasons_programs" TO "authenticated";
GRANT ALL ON TABLE "public"."seasons_programs" TO "service_role";
GRANT ALL ON SEQUENCE "public"."seasons_programs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."seasons_programs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."seasons_programs_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."sinclair_affiliates" TO "anon";
GRANT ALL ON TABLE "public"."sinclair_affiliates" TO "authenticated";
GRANT ALL ON TABLE "public"."sinclair_affiliates" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sinclair_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sinclair_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sinclair_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."timeslots" TO "anon";
GRANT ALL ON TABLE "public"."timeslots" TO "authenticated";
GRANT ALL ON TABLE "public"."timeslots" TO "service_role";
GRANT ALL ON SEQUENCE "public"."timeslot_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."timeslot_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."timeslot_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."timeslot_purchases" TO "anon";
GRANT ALL ON TABLE "public"."timeslot_purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."timeslot_purchases" TO "service_role";
GRANT ALL ON SEQUENCE "public"."timeslot_purchase_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."timeslot_purchase_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."timeslot_purchase_id_seq" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";
RESET ALL;
