CREATE TABLE IF NOT EXISTS "public"."ad_inventory"
(
    "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "media_company_id"       bigint REFERENCES "public"."media_companies" ("id"),
    "total_minutes_per_hour" numeric(5, 2)                          NOT NULL,
    "addressable_percentage" numeric(5, 2)                          NOT NULL,
    "created_at"             timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at"             timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."ad_inventory" OWNER TO "postgres";
ALTER TABLE "public"."ad_inventory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."ad_inventory" FOR SELECT USING (true);
GRANT ALL ON TABLE "public"."ad_inventory" TO "anon", "authenticated", "service_role";