DROP TABLE public.ad_campaigns;

create table public.ad_campaigns (
                                     id bigint generated by default as identity not null,
                                     audience_group_id bigint null,
                                     name text not null,
                                     media_company_id bigint not null,
                                     ad_id bigint not null,
                                     constraint ad_campaign_pkey primary key (id),
                                     constraint ad_campaigns_ad_id_fkey foreign KEY (ad_id) references advertisments (id),
                                     constraint ad_campaigns_audience_group_id_fkey foreign KEY (audience_group_id) references audience_groups (id),
                                     constraint ad_campaigns_media_company_id_fkey foreign KEY (media_company_id) references media_companies (id)
) TABLESPACE pg_default;