CREATE TABLE IF NOT EXISTS "public"."daypart_cpm" (
                                                      "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      "media_company_id" bigint REFERENCES "public"."media_companies"("id"),
                                                      "daypart" text NOT NULL,
                                                      "cpm_value" numeric(10,2) NOT NULL,
                                                      "created_at" timestamp with time zone DEFAULT now() NOT NULL,
                                                      "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."monthly_impressions" (
                                                              "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                              "media_company_id" bigint REFERENCES "public"."media_companies"("id"),
                                                              "month" date NOT NULL,
                                                              "impressions" bigint NOT NULL,
                                                              "created_at" timestamp with time zone DEFAULT now() NOT NULL,
                                                              "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."revenue_recovery_audit" (
                                                                 "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                 "media_company_id" bigint REFERENCES "public"."media_companies"("id"),
                                                                 "total_ad_inventory" numeric(5,2) NOT NULL,
                                                                 "addressable_percentage" numeric(5,2) NOT NULL,
                                                                 "peak_cpm" numeric(10,2) NOT NULL,
                                                                 "low_cpm" numeric(10,2) NOT NULL,
                                                                 "monthly_impressions" bigint NOT NULL,
                                                                 "vertical_type" text NOT NULL,
                                                                 "addressability_gap_index" numeric(5,2) GENERATED ALWAYS AS (100 - addressable_percentage) STORED,
                                                                 "revenue_recovery_potential" numeric(15,2) GENERATED ALWAYS AS (
                                                                     (monthly_impressions * (100 - addressable_percentage) / 100 * (peak_cpm - low_cpm) / 1000) * 12
                                                                     ) STORED,
                                                                 "created_at" timestamp with time zone DEFAULT now() NOT NULL,
                                                                 "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."campaign_performance" (
                                                               "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                               "campaign_id" bigint REFERENCES "public"."ad_campaigns"("id"),
                                                               "date" date NOT NULL,
                                                               "reach" integer NOT NULL,
                                                               "frequency" integer NOT NULL,
                                                               "grp" numeric(10,2) GENERATED ALWAYS AS (reach * frequency / 100) STORED,
                                                               "created_at" timestamp with time zone DEFAULT now() NOT NULL,
                                                               "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Add policies for secure access
ALTER TABLE "public"."daypart_cpm" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."monthly_impressions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."revenue_recovery_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."campaign_performance" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."daypart_cpm" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."monthly_impressions" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."revenue_recovery_audit" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."campaign_performance" FOR SELECT USING (true);

-- Grant permissions
GRANT ALL ON TABLE "public"."daypart_cpm" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."monthly_impressions" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."revenue_recovery_audit" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."campaign_performance" TO "anon", "authenticated", "service_role";